spring.application.name=dpviacep
management.endpoints.web.exposure.include=health,metrics,info,loggers
spring.jpa.open-in-view=false


spring.datasource.url=jdbc:h2:mem:dpviacep
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=